spring.application.name=LaptopShop

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=LaptopShopHSF302;encrypt=false
spring.datasource.username=sa
spring.datasource.password=12345
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
upload.path=uploads/laptop-images
spring.sql.init.mode=always

spring.jpa.defer-datasource-initialization=true
