spring.application.name=LaptopShop

spring.datasource.url=jdbc:sqlserver://localhost\\MSSQLSERVER2022:1433;databaseName=LaptopShopHSF302;encrypt=false
spring.datasource.username=sa
spring.datasource.password=12345
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
